### ISSUE TITLE
Feature request: ability to select file to replace response body

### ISSUE THREAD

**Issue by matejdro** [Chimerapps/niddler-ui#34]
Currently to replace response body, I have to paste long body response string into that (comparably) tiny text box. It would be nice if I could pick local html/json file instead and Niddler would read from that file when serving the response.

As an added bonus, this would also make editing the response much easier since I would only need to edit the file (no need to touch Niddler UI for changing response body).

**Comment by NicolaVerbeeck** [comment]
I have started development for this, this will live next to the rewrite, like charles' mapLocal feature (which will be supported import/export format).
The side effect for this is that changing the response status is not supported for this feature. (as this is not compatible with anything charles has in terms of import/export). If this is an issue, we can always make changes which are not compatible with charles, though that is not my preferred approach right now

**Comment by NicolaVerbeeck** [comment]
An initial preview version of this feature has been submitted to intelliJ for approval. For this you need to upgrade to the java/kotlin version of the libraries at least 1.5.5 or the dart version at least 1.1.0.
Feedback about the feature is appreciated!

**Comment by matejdro** [comment]
Thanks.

From first testing, it seems to work great. Two minor things I've noticed:

1. It is a chore to always chop down full URL into host, path etc. to fit into that mapping dialog box. With regular rules I'm bypassing this dialog box by right clicking on request and selecting "Add request rewrite rule", but this does not work with mappings. Ability to paste whole URL somewhere (which would automatically fill relevant boxes) would be super helpful.
2. Ability to label mappings would be useful

Also I got this exception at some point, but it did not seem to affect anything:

```
java.lang.IllegalStateException: it must not be null
	at com.android.tools.idea.editors.literals.CompilerLiveLiteralsManager$findAsync$3.accept(CompilerLiveLiteralsManager.kt:100)
	at com.android.tools.idea.editors.literals.CompilerLiveLiteralsManager$findAsync$3.accept(CompilerLiveLiteralsManager.kt:99)
	at org.jetbrains.concurrency.AsyncPromise$onSuccess$1.accept(AsyncPromise.kt:84)
	at org.jetbrains.concurrency.AsyncPromise$onSuccess$1.accept(AsyncPromise.kt:16)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:883)
	at java.base/java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2251)
	at org.jetbrains.concurrency.AsyncPromise.onSuccess(AsyncPromise.kt:78)
	at org.jetbrains.concurrency.AsyncPromise.onSuccess(AsyncPromise.kt:16)
	at com.android.tools.idea.editors.literals.CompilerLiveLiteralsManager.findAsync(CompilerLiveLiteralsManager.kt:99)
	at com.android.tools.idea.editors.literals.LiveLiteralsService.addDocumentTracking(LiveLiteralsService.kt:388)
	at com.android.tools.idea.editors.literals.LiveLiteralsService.activateTracking(LiveLiteralsService.kt:436)
	at com.android.tools.idea.editors.literals.LiveLiteralsService.access$activateTracking(LiveLiteralsService.kt:120)
	at com.android.tools.idea.editors.literals.LiveLiteralsService$onAvailabilityChange$1.run(LiveLiteralsService.kt:331)
	at com.intellij.openapi.project.DumbServiceImpl.doUnsafeRunWhenSmart(DumbServiceImpl.java:254)
	at com.intellij.openapi.project.DumbServiceImpl.lambda$doUnsafeRunWhenSmart$2(DumbServiceImpl.java:257)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:216)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:24)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:199)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:828)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:330)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:85)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:134)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:47)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:190)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:976)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:843)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:454)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:762)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:453)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:828)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:501)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:117)
	at java.desktop/java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:190)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:235)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:233)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.desktop/java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:233)
	at java.desktop/java.awt.Dialog.show(Dialog.java:1063)
	at java.desktop/java.awt.Component.show(Component.java:1732)
	at java.desktop/java.awt.Component.setVisible(Component.java:1679)
	at java.desktop/java.awt.Window.setVisible(Window.java:1032)
	at java.desktop/java.awt.Dialog.setVisible(Dialog.java:998)
	at com.chimerapps.niddler.ui.debugging.rewrite.RewriteDialog$Companion.show(RewriteDialog.kt:31)
	at com.chimerapps.niddler.ui.NiddlerToolWindow$setupViewActions$configureDebuggerAction$1.invoke(NiddlerToolWindow.kt:158)
	at com.chimerapps.niddler.ui.NiddlerToolWindow$setupViewActions$configureDebuggerAction$1.invoke(NiddlerToolWindow.kt:157)
	at com.chimerapps.niddler.ui.actions.DisableableAction.actionPerformed(DisableableAction.kt:20)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:281)
	at com.intellij.openapi.actionSystem.impl.ActionButton.actionPerformed(ActionButton.java:209)
	at com.intellij.openapi.actionSystem.impl.ActionButton.performAction(ActionButton.java:177)
	at com.intellij.openapi.actionSystem.impl.ActionButton.performAction(ActionButton.java:160)
	at com.intellij.openapi.actionSystem.impl.ActionButton.processMouseEvent(ActionButton.java:477)
	at java.desktop/java.awt.Component.processEvent(Component.java:6417)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5027)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4859)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2784)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4859)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:976)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:911)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:840)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:454)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:773)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:453)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:828)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:507)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by NicolaVerbeeck** [comment]
I have created 2 issues for point 1: #42 and #43

For 2, this will cause it to no longer be compatible witch charles import/export. I may still add them and just default/skip those items when importing or exporting but this has a lower prio than the other things :)

If you manage to make the crash you see here reproducable I can try to narrow it down, though this looks like a platform bug

**Comment by NicolaVerbeeck** [comment]
2.12.0 is in review with #42 and #43
